export const apiCallConstant = {
    API_CALL_PENDING: 'CATEGORY_CALL_PENDING',
    API_CALL_SUCCESS: 'CATEGORY_CALL_SUCCESS',
    API_CALL_FAILURE: 'CATEGORY_CALL_FAILURE',

    USERS_CALL_PENDING: 'USERS_CALL_PENDING',
    USERS_CALL_SUCCESS: 'USERS_CALL_SUCCESS',
    USERS_CALL_FAILURE: 'USERS_CALL_FAILURE',
}